contact_links:
  - name: Provide feedback to our dbt package team
    url: https://www.surveymonkey.com/r/DQ7K7WW
    about: Fill out our survey form to provide valuable feedback to the Fivetran team developing and maintaining the dbt packages.
  - name: Fivetran connector question
    url: https://support.fivetran.com/hc
    about: Have a question about your connector? Check out the Fivetran support portal for more details.
  - name: What is dbt
    url: https://docs.getdbt.com/docs/introduction
    about: Check out the dbt docs for all dbt related information
  - name: Hang out in dbt Slack
    url: https://www.getdbt.com/community/
    about: Have a question or just want to chat with fellow data friends, join dbt Slack and hangout in the tools-fivetran channel with us!
